CREATE TABLE IF NOT EXISTS locations(
    location_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    location_uuid UUID NOT NULL UNIQUE,
    user_uuid UUID REFERENCES public.users(user_uuid) NOT NULL,
    name TEXT NOT NULL,
    beds INT NOT NULL,
    description TEXT NOT NULL,
    beds TEXT NOT NULL,
    address_street TEXT NOT NULL,
    address_apartment_number TEXT,
    address_state TEXT,
    address_country TEXT NOT NULL,
    image1 BYTEA,
    image2 BYTEA,
    image3 BYTEA,
    image4 BYTEA,
    image5 BYTEA,
    image6 BYTEA,
    image7 BYTEA,
    image8 BYTEA,
    image9 BYTEA,
    image10 BYTEA,
    is_active BOOL DEFAULT FALSE,
    created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_on TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

