CREATE TABLE IF NOT EXISTS locations(
    location_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    location_uuid UUID NOT NULL UNIQUE,
    user_uuid UUID REFERENCES public.users(user_uuid) NOT NULL,
    name TEXT NOT NULL,
    beds INT NOT NULL,
    description TEXT NOT NULL,
    address_city TEXT NOT NULL,
    address_street TEXT NOT NULL,
    address_apartment_number TEXT,
    address_state TEXT,
    address_country TEXT NOT NULL,
    image1 TEXT NOT NULL,
    image2 TEXT,
    image3 TEXT,
    image4 TEXT,
    image5 TEXT,
    image6 TEXT,
    image7 TEXT,
    image8 TEXT,
    image9 TEXT,
    image10 TEXT,
    rating FLOAT,
    is_active BOOL DEFAULT TRUE,
    created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_on TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

